import { writable } from 'svelte/store'

/**
 * Edge-specificity artifact for v2 ranking (Q7-Q9): inverted edge-use buckets
 * from static/data/edge-specificity.json, generated by
 * tests/gen-edge-specificity.mjs from static/data/fk-map.json.
 *
 * The artifact is fetched once and cached at module level (like fkMap.js).
 * The pathfinder reads it via getSpecificityMap() and degrades silently to an
 * empty map (everything bucket 3 = rare) if the search runs before the load
 * finishes — the find page awaits loadSpecificity() ahead of every search, so
 * in practice the map is always present when paths are ranked.
 */

/** @type {Record<string, number> | null} */
let specMap = null

export const specificityLoadState = writable(/** @type {'idle'|'loading'|'ready'|'error'} */ ('idle'))
export const specificityLoadError = writable('')

export async function loadSpecificity() {
  if (specMap) {
    specificityLoadState.set('ready')
    return
  }
  specificityLoadState.set('loading')
  try {
    const res = await fetch('/data/edge-specificity.json')
    if (!res.ok) throw new Error(`HTTP ${res.status}`)
    specMap = await res.json()
    specificityLoadState.set('ready')
  } catch (err) {
    specificityLoadError.set(err instanceof Error ? err.message : String(err))
    specificityLoadState.set('error')
  }
}

/**
 * @returns {Record<string, number> | null} the specificity map, or null when
 *   not loaded yet (absent keys are bucket 3 = rare)
 */
export function getSpecificityMap() {
  return specMap
}